// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// AgentResponse defines model for AgentResponse.
type AgentResponse struct {
	Body     interface{} `json:"body"`
	From     string      `json:"from"`
	Id       string      `json:"id"`
	ThreadID string      `json:"threadID"`
	To       string      `json:"to"`
	Typ      string      `json:"typ"`
	Type     string      `json:"type"`
}

// CreateAuthRequestRequest defines model for CreateAuthRequestRequest.
type CreateAuthRequestRequest struct {
	CredentialSchema      string                 `json:"credentialSchema"`
	CredentialSubject     map[string]interface{} `json:"credentialSubject"`
	Expiration            *int64                 `json:"expiration,omitempty"`
	MerklizedRootPosition *string                `json:"merklizedRootPosition,omitempty"`
	RevNonce              *uint64                `json:"revNonce,omitempty"`
	SubjectPosition       *string                `json:"subjectPosition,omitempty"`
	Type                  string                 `json:"type"`
	Version               *uint32                `json:"version,omitempty"`
}

// CreateAuthRequestResponse defines model for CreateAuthRequestResponse.
type CreateAuthRequestResponse struct {
	Id string `json:"id"`
}

// CreateClaimRequest defines model for CreateClaimRequest.
type CreateClaimRequest struct {
	CredentialSchema      string                 `json:"credentialSchema"`
	CredentialSubject     map[string]interface{} `json:"credentialSubject"`
	Expiration            *int64                 `json:"expiration,omitempty"`
	MerklizedRootPosition *string                `json:"merklizedRootPosition,omitempty"`
	RevNonce              *uint64                `json:"revNonce,omitempty"`
	SubjectPosition       *string                `json:"subjectPosition,omitempty"`
	Type                  string                 `json:"type"`
	Version               *uint32                `json:"version,omitempty"`
}

// CreateClaimResponse defines model for CreateClaimResponse.
type CreateClaimResponse struct {
	Id string `json:"id"`
}

// CreateIdentityRequest defines model for CreateIdentityRequest.
type CreateIdentityRequest struct {
	DidMetadata struct {
		Blockchain string `json:"blockchain"`
		Method     string `json:"method"`
		Network    string `json:"network"`
	} `json:"didMetadata"`
}

// CreateIdentityResponse defines model for CreateIdentityResponse.
type CreateIdentityResponse struct {
	Identifier *string        `json:"identifier,omitempty"`
	State      *IdentityState `json:"state,omitempty"`
}

// CreateQueryRequestRequest defines model for CreateQueryRequestRequest.
type CreateQueryRequestRequest struct {
	CredentialSchema      string                 `json:"credentialSchema"`
	CredentialSubject     map[string]interface{} `json:"credentialSubject"`
	Expiration            *int64                 `json:"expiration,omitempty"`
	MerklizedRootPosition *string                `json:"merklizedRootPosition,omitempty"`
	RevNonce              *uint64                `json:"revNonce,omitempty"`
	SubjectPosition       *string                `json:"subjectPosition,omitempty"`
	Type                  string                 `json:"type"`
	Version               *uint32                `json:"version,omitempty"`
}

// CreateQueryRequestResponse defines model for CreateQueryRequestResponse.
type CreateQueryRequestResponse struct {
	Id string `json:"id"`
}

// CredentialSchema defines model for CredentialSchema.
type CredentialSchema struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

// GenerateProofRequest defines model for GenerateProofRequest.
type GenerateProofRequest struct {
	Body GenerateProofRequestBody `json:"body"`
	From string                   `json:"from"`
	Id   string                   `json:"id"`
	Thid string                   `json:"thid"`
	To   string                   `json:"to"`
	Typ  string                   `json:"typ"`
	Type string                   `json:"type"`
}

// GenerateProofRequestBody defines model for GenerateProofRequestBody.
type GenerateProofRequestBody struct {
	CallbackUrl string                       `json:"callbackUrl"`
	Message     string                       `json:"message"`
	Reason      string                       `json:"reason"`
	Scope       *[]GenerateProofRequestScope `json:"scope,omitempty"`
}

// GenerateProofRequestQuery defines model for GenerateProofRequestQuery.
type GenerateProofRequestQuery struct {
	AllowedIssuers    []string               `json:"allowedIssuers"`
	Context           string                 `json:"context"`
	CredentialSubject map[string]interface{} `json:"credentialSubject"`
	Type              string                 `json:"type"`
}

// GenerateProofRequestScope defines model for GenerateProofRequestScope.
type GenerateProofRequestScope struct {
	CircuitId string                    `json:"circuitId"`
	Id        string                    `json:"id"`
	Query     GenerateProofRequestQuery `json:"query"`
}

// GenerateProofResponse defines model for GenerateProofResponse.
type GenerateProofResponse struct {
	Proof      *GenerateProofResponseProof `json:"proof,omitempty"`
	PubSignals *[]string                   `json:"pub_signals"`
}

// GenerateProofResponseProof defines model for GenerateProofResponseProof.
type GenerateProofResponseProof struct {
	PiA      []string      `json:"pi_a"`
	PiB      []StringArray `json:"pi_b"`
	PiC      []string      `json:"pi_c"`
	Protocol string        `json:"protocol"`
}

// GenericErrorMessage defines model for GenericErrorMessage.
type GenericErrorMessage struct {
	Message string `json:"message"`
}

// GetClaimQrCodeResponse defines model for GetClaimQrCodeResponse.
type GetClaimQrCodeResponse struct {
	Body struct {
		Credentials []struct {
			Description string `json:"description"`
			Id          string `json:"id"`
		} `json:"credentials"`
		Url string `json:"url"`
	} `json:"body"`
	From string `json:"from"`
	Id   string `json:"id"`
	Thid string `json:"thid"`
	To   string `json:"to"`
	Typ  string `json:"typ"`
	Type string `json:"type"`
}

// GetClaimResponse defines model for GetClaimResponse.
type GetClaimResponse struct {
	Context           []string               `json:"@context"`
	CredentialSchema  CredentialSchema       `json:"credentialSchema"`
	CredentialStatus  interface{}            `json:"credentialStatus"`
	CredentialSubject map[string]interface{} `json:"credentialSubject"`
	Expiration        *time.Time             `json:"expiration,omitempty"`
	Id                string                 `json:"id"`
	IssuanceDate      *time.Time             `json:"issuanceDate,omitempty"`
	Issuer            string                 `json:"issuer"`
	Proof             interface{}            `json:"proof"`
	Type              []string               `json:"type"`
}

// GetClaimsResponse defines model for GetClaimsResponse.
type GetClaimsResponse = []GetClaimResponse

// Health defines model for Health.
type Health map[string]bool

// IdentityState defines model for IdentityState.
type IdentityState struct {
	BlockNumber        *int      `json:"blockNumber,omitempty"`
	BlockTimestamp     *int      `json:"blockTimestamp,omitempty"`
	ClaimsTreeRoot     *string   `json:"claimsTreeRoot,omitempty"`
	CreatedAt          time.Time `json:"createdAt"`
	Identifier         string    `json:"-"`
	ModifiedAt         time.Time `json:"modifiedAt"`
	PreviousState      *string   `json:"previousState,omitempty"`
	RevocationTreeRoot *string   `json:"revocationTreeRoot,omitempty"`
	RootOfRoots        *string   `json:"rootOfRoots,omitempty"`
	State              *string   `json:"state,omitempty"`
	StateID            int64     `json:"-"`
	Status             string    `json:"status"`
	TxID               *string   `json:"txID,omitempty"`
}

// PublishIdentityStateResponse defines model for PublishIdentityStateResponse.
type PublishIdentityStateResponse struct {
	ClaimsTreeRoot     *string `json:"claimsTreeRoot,omitempty"`
	RevocationTreeRoot *string `json:"revocationTreeRoot,omitempty"`
	RootOfRoots        *string `json:"rootOfRoots,omitempty"`
	State              *string `json:"state,omitempty"`
	TxID               *string `json:"txID,omitempty"`
}

// ReturnCreateIdentityOptionsRequest defines model for ReturnCreateIdentityOptionsRequest.
type ReturnCreateIdentityOptionsRequest = map[string]interface{}

// ReturnCreateIdentityOptionsResponse defines model for ReturnCreateIdentityOptionsResponse.
type ReturnCreateIdentityOptionsResponse = map[string]interface{}

// RevocationStatusResponse defines model for RevocationStatusResponse.
type RevocationStatusResponse struct {
	Issuer struct {
		ClaimsTreeRoot     *string `json:"claimsTreeRoot,omitempty"`
		RevocationTreeRoot *string `json:"revocationTreeRoot,omitempty"`
		RootOfRoots        *string `json:"rootOfRoots,omitempty"`
		State              *string `json:"state,omitempty"`
	} `json:"issuer"`
	Mtp struct {
		Existence bool `json:"existence"`
		NodeAux   *struct {
			Key   *string `json:"key,omitempty"`
			Value *string `json:"value,omitempty"`
		} `json:"node_aux,omitempty"`
		Siblings *[]string `json:"siblings"`
	} `json:"mtp"`
}

// RevokeClaimResponse defines model for RevokeClaimResponse.
type RevokeClaimResponse struct {
	Message string `json:"message"`
}

// VerifyProofRequest defines model for VerifyProofRequest.
type VerifyProofRequest struct {
	GenerateProofRequest  GenerateProofRequest  `json:"generateProofRequest"`
	GenerateProofResponse GenerateProofResponse `json:"generateProofResponse"`
}

// VerifyProofResponse defines model for VerifyProofResponse.
type VerifyProofResponse struct {
	Verified bool `json:"verified"`
}

// StringArray defines model for stringArray.
type StringArray = []string

// PathClaim defines model for pathClaim.
type PathClaim = string

// PathIdentifier defines model for pathIdentifier.
type PathIdentifier = string

// PathNonce defines model for pathNonce.
type PathNonce = int64

// N400 defines model for 400.
type N400 = GenericErrorMessage

// N401 defines model for 401.
type N401 = GenericErrorMessage

// N404 defines model for 404.
type N404 = GenericErrorMessage

// N422 defines model for 422.
type N422 = GenericErrorMessage

// N500 defines model for 500.
type N500 = GenericErrorMessage

// N500CreateIdentity defines model for 500-CreateIdentity.
type N500CreateIdentity struct {
	Code      *int    `json:"code,omitempty"`
	Error     *string `json:"error,omitempty"`
	RequestID *string `json:"requestID,omitempty"`
}

// AgentTextBody defines parameters for Agent.
type AgentTextBody = string

// GetClaimsParams defines parameters for GetClaims.
type GetClaimsParams struct {
	// SchemaType Filter per schema type. Example - KYCAgeCredential
	SchemaType *string `form:"schemaType,omitempty" json:"schemaType,omitempty"`

	// SchemaHash Filter per schema hash. Example - c9b2370371b7fa8b3dab2a5ba81b6838
	SchemaHash *string `form:"schemaHash,omitempty" json:"schemaHash,omitempty"`

	// Subject Filter per subject. Example - did:polygonid:polygon:mumbai:2qE1BZ7gcmEoP2KppvFPCZqyzyb5tK9T6Gec5HFANQ
	Subject *string `form:"subject,omitempty" json:"subject,omitempty"`

	// Revoked Filter per claims revoked or not - Example - true.
	Revoked *bool `form:"revoked,omitempty" json:"revoked,omitempty"`

	// Self Filter per retrieve claims of the provided identifier. Example - true
	Self *bool `form:"self,omitempty" json:"self,omitempty"`

	// QueryField Filter inside the data of the claim.
	QueryField *string `form:"query_field,omitempty" json:"query_field,omitempty"`
}

// AgentTextRequestBody defines body for Agent for text/plain ContentType.
type AgentTextRequestBody = AgentTextBody

// ReturnCreateIdentityOptionsJSONRequestBody defines body for ReturnCreateIdentityOptions for application/json ContentType.
type ReturnCreateIdentityOptionsJSONRequestBody = ReturnCreateIdentityOptionsRequest

// CreateIdentityJSONRequestBody defines body for CreateIdentity for application/json ContentType.
type CreateIdentityJSONRequestBody = CreateIdentityRequest

// CreateAuthRequestJSONRequestBody defines body for CreateAuthRequest for application/json ContentType.
type CreateAuthRequestJSONRequestBody = CreateAuthRequestRequest

// CreateClaimJSONRequestBody defines body for CreateClaim for application/json ContentType.
type CreateClaimJSONRequestBody = CreateClaimRequest

// GenerateProofJSONRequestBody defines body for GenerateProof for application/json ContentType.
type GenerateProofJSONRequestBody = GenerateProofRequest

// CreateQueryRequestJSONRequestBody defines body for CreateQueryRequest for application/json ContentType.
type CreateQueryRequestJSONRequestBody = CreateQueryRequestRequest

// VerifyProofJSONRequestBody defines body for VerifyProof for application/json ContentType.
type VerifyProofJSONRequestBody = VerifyProofRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the documentation
	// (GET /)
	GetDocumentation(w http.ResponseWriter, r *http.Request)
	// Get the documentation yaml file
	// (GET /static/docs/api/api.yaml)
	GetYaml(w http.ResponseWriter, r *http.Request)
	// Healthcheck
	// (GET /status)
	Health(w http.ResponseWriter, r *http.Request)
	// Agent
	// (POST /v1/agent)
	Agent(w http.ResponseWriter, r *http.Request)
	// Get Identities
	// (GET /v1/identities)
	GetIdentities(w http.ResponseWriter, r *http.Request)
	// Options request
	// (OPTIONS /v1/identities)
	ReturnCreateIdentityOptions(w http.ResponseWriter, r *http.Request)
	// Create Identity
	// (POST /v1/identities)
	CreateIdentity(w http.ResponseWriter, r *http.Request)
	// Create Auth Request
	// (POST /v1/{identifier}/auth-reqs)
	CreateAuthRequest(w http.ResponseWriter, r *http.Request, identifier PathIdentifier)
	// Get Claims
	// (GET /v1/{identifier}/claims)
	GetClaims(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, params GetClaimsParams)
	// Create Claim
	// (POST /v1/{identifier}/claims)
	CreateClaim(w http.ResponseWriter, r *http.Request, identifier PathIdentifier)
	// Get Revocation Status
	// (GET /v1/{identifier}/claims/revocation/status/{nonce})
	GetRevocationStatus(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, nonce PathNonce)
	// Revoke Claim
	// (POST /v1/{identifier}/claims/revoke/{nonce})
	RevokeClaim(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, nonce PathNonce)
	// Get Claim
	// (GET /v1/{identifier}/claims/{id})
	GetClaim(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, id PathClaim)
	// Get Claim QR code
	// (GET /v1/{identifier}/claims/{id}/qrcode)
	GetClaimQrCode(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, id PathClaim)
	// Request a proof generation
	// (POST /v1/{identifier}/generate-proof)
	GenerateProof(w http.ResponseWriter, r *http.Request, identifier PathIdentifier)
	// Create Query Request
	// (POST /v1/{identifier}/query-reqs)
	CreateQueryRequest(w http.ResponseWriter, r *http.Request, identifier PathIdentifier)
	// Publish Identity State
	// (POST /v1/{identifier}/state/publish)
	PublishIdentityState(w http.ResponseWriter, r *http.Request, identifier PathIdentifier)
	// Request a proof verification
	// (POST /v1/{identifier}/verify-proof)
	VerifyProof(w http.ResponseWriter, r *http.Request, identifier PathIdentifier)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDocumentation operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentation(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetYaml operation middleware
func (siw *ServerInterfaceWrapper) GetYaml(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetYaml(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// Agent operation middleware
func (siw *ServerInterfaceWrapper) Agent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Agent(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetIdentities operation middleware
func (siw *ServerInterfaceWrapper) GetIdentities(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIdentities(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ReturnCreateIdentityOptions operation middleware
func (siw *ServerInterfaceWrapper) ReturnCreateIdentityOptions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReturnCreateIdentityOptions(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateIdentity operation middleware
func (siw *ServerInterfaceWrapper) CreateIdentity(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIdentity(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateAuthRequest operation middleware
func (siw *ServerInterfaceWrapper) CreateAuthRequest(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAuthRequest(w, r, identifier)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetClaims operation middleware
func (siw *ServerInterfaceWrapper) GetClaims(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClaimsParams

	// ------------- Optional query parameter "schemaType" -------------

	err = runtime.BindQueryParameter("form", true, false, "schemaType", r.URL.Query(), &params.SchemaType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schemaType", Err: err})
		return
	}

	// ------------- Optional query parameter "schemaHash" -------------

	err = runtime.BindQueryParameter("form", true, false, "schemaHash", r.URL.Query(), &params.SchemaHash)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schemaHash", Err: err})
		return
	}

	// ------------- Optional query parameter "subject" -------------

	err = runtime.BindQueryParameter("form", true, false, "subject", r.URL.Query(), &params.Subject)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject", Err: err})
		return
	}

	// ------------- Optional query parameter "revoked" -------------

	err = runtime.BindQueryParameter("form", true, false, "revoked", r.URL.Query(), &params.Revoked)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "revoked", Err: err})
		return
	}

	// ------------- Optional query parameter "self" -------------

	err = runtime.BindQueryParameter("form", true, false, "self", r.URL.Query(), &params.Self)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "self", Err: err})
		return
	}

	// ------------- Optional query parameter "query_field" -------------

	err = runtime.BindQueryParameter("form", true, false, "query_field", r.URL.Query(), &params.QueryField)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query_field", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClaims(w, r, identifier, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateClaim operation middleware
func (siw *ServerInterfaceWrapper) CreateClaim(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateClaim(w, r, identifier)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRevocationStatus operation middleware
func (siw *ServerInterfaceWrapper) GetRevocationStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	// ------------- Path parameter "nonce" -------------
	var nonce PathNonce

	err = runtime.BindStyledParameterWithLocation("simple", false, "nonce", runtime.ParamLocationPath, chi.URLParam(r, "nonce"), &nonce)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nonce", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRevocationStatus(w, r, identifier, nonce)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RevokeClaim operation middleware
func (siw *ServerInterfaceWrapper) RevokeClaim(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	// ------------- Path parameter "nonce" -------------
	var nonce PathNonce

	err = runtime.BindStyledParameterWithLocation("simple", false, "nonce", runtime.ParamLocationPath, chi.URLParam(r, "nonce"), &nonce)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nonce", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeClaim(w, r, identifier, nonce)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetClaim operation middleware
func (siw *ServerInterfaceWrapper) GetClaim(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id PathClaim

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClaim(w, r, identifier, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetClaimQrCode operation middleware
func (siw *ServerInterfaceWrapper) GetClaimQrCode(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id PathClaim

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClaimQrCode(w, r, identifier, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GenerateProof operation middleware
func (siw *ServerInterfaceWrapper) GenerateProof(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateProof(w, r, identifier)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateQueryRequest operation middleware
func (siw *ServerInterfaceWrapper) CreateQueryRequest(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQueryRequest(w, r, identifier)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PublishIdentityState operation middleware
func (siw *ServerInterfaceWrapper) PublishIdentityState(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishIdentityState(w, r, identifier)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VerifyProof operation middleware
func (siw *ServerInterfaceWrapper) VerifyProof(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier PathIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "identifier", runtime.ParamLocationPath, chi.URLParam(r, "identifier"), &identifier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyProof(w, r, identifier)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.GetDocumentation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/static/docs/api/api.yaml", wrapper.GetYaml)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/status", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/agent", wrapper.Agent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities", wrapper.GetIdentities)
	})
	r.Group(func(r chi.Router) {
		r.Options(options.BaseURL+"/v1/identities", wrapper.ReturnCreateIdentityOptions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/identities", wrapper.CreateIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/{identifier}/auth-reqs", wrapper.CreateAuthRequest)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/{identifier}/claims", wrapper.GetClaims)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/{identifier}/claims", wrapper.CreateClaim)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/{identifier}/claims/revocation/status/{nonce}", wrapper.GetRevocationStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/{identifier}/claims/revoke/{nonce}", wrapper.RevokeClaim)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/{identifier}/claims/{id}", wrapper.GetClaim)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/{identifier}/claims/{id}/qrcode", wrapper.GetClaimQrCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/{identifier}/generate-proof", wrapper.GenerateProof)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/{identifier}/query-reqs", wrapper.CreateQueryRequest)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/{identifier}/state/publish", wrapper.PublishIdentityState)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/{identifier}/verify-proof", wrapper.VerifyProof)
	})

	return r
}

type N400JSONResponse GenericErrorMessage

type N401JSONResponse GenericErrorMessage

type N404JSONResponse GenericErrorMessage

type N422JSONResponse GenericErrorMessage

type N500JSONResponse GenericErrorMessage

type N500CreateIdentityJSONResponse struct {
	Code      *int    `json:"code,omitempty"`
	Error     *string `json:"error,omitempty"`
	RequestID *string `json:"requestID,omitempty"`
}

type GetDocumentationRequestObject struct {
}

type GetDocumentationResponseObject interface {
	VisitGetDocumentationResponse(w http.ResponseWriter) error
}

type GetDocumentation200Response struct {
}

func (response GetDocumentation200Response) VisitGetDocumentationResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetYamlRequestObject struct {
}

type GetYamlResponseObject interface {
	VisitGetYamlResponse(w http.ResponseWriter) error
}

type GetYaml200Response struct {
}

func (response GetYaml200Response) VisitGetYamlResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse Health

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Health500JSONResponse struct{ N500JSONResponse }

func (response Health500JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AgentRequestObject struct {
	Body *AgentTextRequestBody
}

type AgentResponseObject interface {
	VisitAgentResponse(w http.ResponseWriter) error
}

type Agent200JSONResponse AgentResponse

func (response Agent200JSONResponse) VisitAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Agent400JSONResponse struct{ N400JSONResponse }

func (response Agent400JSONResponse) VisitAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Agent500JSONResponse struct{ N500JSONResponse }

func (response Agent500JSONResponse) VisitAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetIdentitiesRequestObject struct {
}

type GetIdentitiesResponseObject interface {
	VisitGetIdentitiesResponse(w http.ResponseWriter) error
}

type GetIdentities200JSONResponse []string

func (response GetIdentities200JSONResponse) VisitGetIdentitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetIdentities401JSONResponse struct{ N401JSONResponse }

func (response GetIdentities401JSONResponse) VisitGetIdentitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetIdentities500JSONResponse struct{ N500JSONResponse }

func (response GetIdentities500JSONResponse) VisitGetIdentitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ReturnCreateIdentityOptionsRequestObject struct {
	Body *ReturnCreateIdentityOptionsJSONRequestBody
}

type ReturnCreateIdentityOptionsResponseObject interface {
	VisitReturnCreateIdentityOptionsResponse(w http.ResponseWriter) error
}

type ReturnCreateIdentityOptions200ResponseHeaders struct {
	AccessControlAllowOrigin interface{}
}

type ReturnCreateIdentityOptions200JSONResponse struct {
	Body    ReturnCreateIdentityOptionsResponse
	Headers ReturnCreateIdentityOptions200ResponseHeaders
}

func (response ReturnCreateIdentityOptions200JSONResponse) VisitReturnCreateIdentityOptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Access-Control-Allow-Origin", fmt.Sprint(response.Headers.AccessControlAllowOrigin))
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ReturnCreateIdentityOptions500JSONResponse struct{ N500CreateIdentityJSONResponse }

func (response ReturnCreateIdentityOptions500JSONResponse) VisitReturnCreateIdentityOptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateIdentityRequestObject struct {
	Body *CreateIdentityJSONRequestBody
}

type CreateIdentityResponseObject interface {
	VisitCreateIdentityResponse(w http.ResponseWriter) error
}

type CreateIdentity201JSONResponse CreateIdentityResponse

func (response CreateIdentity201JSONResponse) VisitCreateIdentityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateIdentity400JSONResponse struct{ N400JSONResponse }

func (response CreateIdentity400JSONResponse) VisitCreateIdentityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateIdentity401JSONResponse struct{ N401JSONResponse }

func (response CreateIdentity401JSONResponse) VisitCreateIdentityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateIdentity500JSONResponse struct{ N500CreateIdentityJSONResponse }

func (response CreateIdentity500JSONResponse) VisitCreateIdentityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateAuthRequestRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Body       *CreateAuthRequestJSONRequestBody
}

type CreateAuthRequestResponseObject interface {
	VisitCreateAuthRequestResponse(w http.ResponseWriter) error
}

type CreateAuthRequest201JSONResponse CreateAuthRequestResponse

func (response CreateAuthRequest201JSONResponse) VisitCreateAuthRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateAuthRequest400JSONResponse struct{ N400JSONResponse }

func (response CreateAuthRequest400JSONResponse) VisitCreateAuthRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAuthRequest401JSONResponse struct{ N401JSONResponse }

func (response CreateAuthRequest401JSONResponse) VisitCreateAuthRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateAuthRequest422JSONResponse struct{ N422JSONResponse }

func (response CreateAuthRequest422JSONResponse) VisitCreateAuthRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateAuthRequest500JSONResponse struct{ N500JSONResponse }

func (response CreateAuthRequest500JSONResponse) VisitCreateAuthRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimsRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Params     GetClaimsParams
}

type GetClaimsResponseObject interface {
	VisitGetClaimsResponse(w http.ResponseWriter) error
}

type GetClaims200JSONResponse GetClaimsResponse

func (response GetClaims200JSONResponse) VisitGetClaimsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetClaims400JSONResponse struct{ N400JSONResponse }

func (response GetClaims400JSONResponse) VisitGetClaimsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetClaims401JSONResponse struct{ N401JSONResponse }

func (response GetClaims401JSONResponse) VisitGetClaimsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetClaims500JSONResponse struct{ N500JSONResponse }

func (response GetClaims500JSONResponse) VisitGetClaimsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateClaimRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Body       *CreateClaimJSONRequestBody
}

type CreateClaimResponseObject interface {
	VisitCreateClaimResponse(w http.ResponseWriter) error
}

type CreateClaim201JSONResponse CreateClaimResponse

func (response CreateClaim201JSONResponse) VisitCreateClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateClaim400JSONResponse struct{ N400JSONResponse }

func (response CreateClaim400JSONResponse) VisitCreateClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateClaim401JSONResponse struct{ N401JSONResponse }

func (response CreateClaim401JSONResponse) VisitCreateClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateClaim422JSONResponse struct{ N422JSONResponse }

func (response CreateClaim422JSONResponse) VisitCreateClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateClaim500JSONResponse struct{ N500JSONResponse }

func (response CreateClaim500JSONResponse) VisitCreateClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRevocationStatusRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Nonce      PathNonce      `json:"nonce"`
}

type GetRevocationStatusResponseObject interface {
	VisitGetRevocationStatusResponse(w http.ResponseWriter) error
}

type GetRevocationStatus200JSONResponse RevocationStatusResponse

func (response GetRevocationStatus200JSONResponse) VisitGetRevocationStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRevocationStatus400JSONResponse struct{ N400JSONResponse }

func (response GetRevocationStatus400JSONResponse) VisitGetRevocationStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetRevocationStatus500JSONResponse struct{ N500JSONResponse }

func (response GetRevocationStatus500JSONResponse) VisitGetRevocationStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RevokeClaimRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Nonce      PathNonce      `json:"nonce"`
}

type RevokeClaimResponseObject interface {
	VisitRevokeClaimResponse(w http.ResponseWriter) error
}

type RevokeClaim202JSONResponse RevokeClaimResponse

func (response RevokeClaim202JSONResponse) VisitRevokeClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type RevokeClaim401JSONResponse struct{ N401JSONResponse }

func (response RevokeClaim401JSONResponse) VisitRevokeClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RevokeClaim404JSONResponse struct{ N404JSONResponse }

func (response RevokeClaim404JSONResponse) VisitRevokeClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RevokeClaim500JSONResponse struct{ N500JSONResponse }

func (response RevokeClaim500JSONResponse) VisitRevokeClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Id         PathClaim      `json:"id"`
}

type GetClaimResponseObject interface {
	VisitGetClaimResponse(w http.ResponseWriter) error
}

type GetClaim200JSONResponse GetClaimResponse

func (response GetClaim200JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetClaim400JSONResponse struct{ N400JSONResponse }

func (response GetClaim400JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetClaim401JSONResponse struct{ N401JSONResponse }

func (response GetClaim401JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetClaim404JSONResponse struct{ N404JSONResponse }

func (response GetClaim404JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetClaim500JSONResponse struct{ N500JSONResponse }

func (response GetClaim500JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimQrCodeRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Id         PathClaim      `json:"id"`
}

type GetClaimQrCodeResponseObject interface {
	VisitGetClaimQrCodeResponse(w http.ResponseWriter) error
}

type GetClaimQrCode200JSONResponse GetClaimQrCodeResponse

func (response GetClaimQrCode200JSONResponse) VisitGetClaimQrCodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimQrCode400JSONResponse struct{ N400JSONResponse }

func (response GetClaimQrCode400JSONResponse) VisitGetClaimQrCodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimQrCode404JSONResponse struct{ N404JSONResponse }

func (response GetClaimQrCode404JSONResponse) VisitGetClaimQrCodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimQrCode500JSONResponse struct{ N500JSONResponse }

func (response GetClaimQrCode500JSONResponse) VisitGetClaimQrCodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GenerateProofRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Body       *GenerateProofJSONRequestBody
}

type GenerateProofResponseObject interface {
	VisitGenerateProofResponse(w http.ResponseWriter) error
}

type GenerateProof200JSONResponse GenerateProofResponse

func (response GenerateProof200JSONResponse) VisitGenerateProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GenerateProof400JSONResponse struct{ N400JSONResponse }

func (response GenerateProof400JSONResponse) VisitGenerateProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GenerateProof401JSONResponse struct{ N401JSONResponse }

func (response GenerateProof401JSONResponse) VisitGenerateProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GenerateProof422JSONResponse struct{ N422JSONResponse }

func (response GenerateProof422JSONResponse) VisitGenerateProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GenerateProof500JSONResponse struct{ N500JSONResponse }

func (response GenerateProof500JSONResponse) VisitGenerateProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateQueryRequestRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Body       *CreateQueryRequestJSONRequestBody
}

type CreateQueryRequestResponseObject interface {
	VisitCreateQueryRequestResponse(w http.ResponseWriter) error
}

type CreateQueryRequest201JSONResponse CreateQueryRequestResponse

func (response CreateQueryRequest201JSONResponse) VisitCreateQueryRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateQueryRequest400JSONResponse struct{ N400JSONResponse }

func (response CreateQueryRequest400JSONResponse) VisitCreateQueryRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateQueryRequest401JSONResponse struct{ N401JSONResponse }

func (response CreateQueryRequest401JSONResponse) VisitCreateQueryRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateQueryRequest422JSONResponse struct{ N422JSONResponse }

func (response CreateQueryRequest422JSONResponse) VisitCreateQueryRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateQueryRequest500JSONResponse struct{ N500JSONResponse }

func (response CreateQueryRequest500JSONResponse) VisitCreateQueryRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PublishIdentityStateRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
}

type PublishIdentityStateResponseObject interface {
	VisitPublishIdentityStateResponse(w http.ResponseWriter) error
}

type PublishIdentityState200JSONResponse GenericErrorMessage

func (response PublishIdentityState200JSONResponse) VisitPublishIdentityStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PublishIdentityState202JSONResponse PublishIdentityStateResponse

func (response PublishIdentityState202JSONResponse) VisitPublishIdentityStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type PublishIdentityState400JSONResponse struct{ N400JSONResponse }

func (response PublishIdentityState400JSONResponse) VisitPublishIdentityStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PublishIdentityState401JSONResponse struct{ N401JSONResponse }

func (response PublishIdentityState401JSONResponse) VisitPublishIdentityStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PublishIdentityState500JSONResponse struct{ N500JSONResponse }

func (response PublishIdentityState500JSONResponse) VisitPublishIdentityStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type VerifyProofRequestObject struct {
	Identifier PathIdentifier `json:"identifier"`
	Body       *VerifyProofJSONRequestBody
}

type VerifyProofResponseObject interface {
	VisitVerifyProofResponse(w http.ResponseWriter) error
}

type VerifyProof200JSONResponse VerifyProofResponse

func (response VerifyProof200JSONResponse) VisitVerifyProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VerifyProof400JSONResponse struct{ N400JSONResponse }

func (response VerifyProof400JSONResponse) VisitVerifyProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type VerifyProof401JSONResponse struct{ N401JSONResponse }

func (response VerifyProof401JSONResponse) VisitVerifyProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VerifyProof422JSONResponse struct{ N422JSONResponse }

func (response VerifyProof422JSONResponse) VisitVerifyProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type VerifyProof500JSONResponse struct{ N500JSONResponse }

func (response VerifyProof500JSONResponse) VisitVerifyProofResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get the documentation
	// (GET /)
	GetDocumentation(ctx context.Context, request GetDocumentationRequestObject) (GetDocumentationResponseObject, error)
	// Get the documentation yaml file
	// (GET /static/docs/api/api.yaml)
	GetYaml(ctx context.Context, request GetYamlRequestObject) (GetYamlResponseObject, error)
	// Healthcheck
	// (GET /status)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)
	// Agent
	// (POST /v1/agent)
	Agent(ctx context.Context, request AgentRequestObject) (AgentResponseObject, error)
	// Get Identities
	// (GET /v1/identities)
	GetIdentities(ctx context.Context, request GetIdentitiesRequestObject) (GetIdentitiesResponseObject, error)
	// Options request
	// (OPTIONS /v1/identities)
	ReturnCreateIdentityOptions(ctx context.Context, request ReturnCreateIdentityOptionsRequestObject) (ReturnCreateIdentityOptionsResponseObject, error)
	// Create Identity
	// (POST /v1/identities)
	CreateIdentity(ctx context.Context, request CreateIdentityRequestObject) (CreateIdentityResponseObject, error)
	// Create Auth Request
	// (POST /v1/{identifier}/auth-reqs)
	CreateAuthRequest(ctx context.Context, request CreateAuthRequestRequestObject) (CreateAuthRequestResponseObject, error)
	// Get Claims
	// (GET /v1/{identifier}/claims)
	GetClaims(ctx context.Context, request GetClaimsRequestObject) (GetClaimsResponseObject, error)
	// Create Claim
	// (POST /v1/{identifier}/claims)
	CreateClaim(ctx context.Context, request CreateClaimRequestObject) (CreateClaimResponseObject, error)
	// Get Revocation Status
	// (GET /v1/{identifier}/claims/revocation/status/{nonce})
	GetRevocationStatus(ctx context.Context, request GetRevocationStatusRequestObject) (GetRevocationStatusResponseObject, error)
	// Revoke Claim
	// (POST /v1/{identifier}/claims/revoke/{nonce})
	RevokeClaim(ctx context.Context, request RevokeClaimRequestObject) (RevokeClaimResponseObject, error)
	// Get Claim
	// (GET /v1/{identifier}/claims/{id})
	GetClaim(ctx context.Context, request GetClaimRequestObject) (GetClaimResponseObject, error)
	// Get Claim QR code
	// (GET /v1/{identifier}/claims/{id}/qrcode)
	GetClaimQrCode(ctx context.Context, request GetClaimQrCodeRequestObject) (GetClaimQrCodeResponseObject, error)
	// Request a proof generation
	// (POST /v1/{identifier}/generate-proof)
	GenerateProof(ctx context.Context, request GenerateProofRequestObject) (GenerateProofResponseObject, error)
	// Create Query Request
	// (POST /v1/{identifier}/query-reqs)
	CreateQueryRequest(ctx context.Context, request CreateQueryRequestRequestObject) (CreateQueryRequestResponseObject, error)
	// Publish Identity State
	// (POST /v1/{identifier}/state/publish)
	PublishIdentityState(ctx context.Context, request PublishIdentityStateRequestObject) (PublishIdentityStateResponseObject, error)
	// Request a proof verification
	// (POST /v1/{identifier}/verify-proof)
	VerifyProof(ctx context.Context, request VerifyProofRequestObject) (VerifyProofResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDocumentation operation middleware
func (sh *strictHandler) GetDocumentation(w http.ResponseWriter, r *http.Request) {
	var request GetDocumentationRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocumentation(ctx, request.(GetDocumentationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocumentation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentationResponseObject); ok {
		if err := validResponse.VisitGetDocumentationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetYaml operation middleware
func (sh *strictHandler) GetYaml(w http.ResponseWriter, r *http.Request) {
	var request GetYamlRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetYaml(ctx, request.(GetYamlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetYaml")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetYamlResponseObject); ok {
		if err := validResponse.VisitGetYamlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// Health operation middleware
func (sh *strictHandler) Health(w http.ResponseWriter, r *http.Request) {
	var request HealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// Agent operation middleware
func (sh *strictHandler) Agent(w http.ResponseWriter, r *http.Request) {
	var request AgentRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	body := AgentTextRequestBody(data)
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Agent(ctx, request.(AgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Agent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AgentResponseObject); ok {
		if err := validResponse.VisitAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetIdentities operation middleware
func (sh *strictHandler) GetIdentities(w http.ResponseWriter, r *http.Request) {
	var request GetIdentitiesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIdentities(ctx, request.(GetIdentitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIdentities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIdentitiesResponseObject); ok {
		if err := validResponse.VisitGetIdentitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// ReturnCreateIdentityOptions operation middleware
func (sh *strictHandler) ReturnCreateIdentityOptions(w http.ResponseWriter, r *http.Request) {
	var request ReturnCreateIdentityOptionsRequestObject

	var body ReturnCreateIdentityOptionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReturnCreateIdentityOptions(ctx, request.(ReturnCreateIdentityOptionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReturnCreateIdentityOptions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReturnCreateIdentityOptionsResponseObject); ok {
		if err := validResponse.VisitReturnCreateIdentityOptionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// CreateIdentity operation middleware
func (sh *strictHandler) CreateIdentity(w http.ResponseWriter, r *http.Request) {
	var request CreateIdentityRequestObject

	var body CreateIdentityJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateIdentity(ctx, request.(CreateIdentityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateIdentity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateIdentityResponseObject); ok {
		if err := validResponse.VisitCreateIdentityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// CreateAuthRequest operation middleware
func (sh *strictHandler) CreateAuthRequest(w http.ResponseWriter, r *http.Request, identifier PathIdentifier) {
	var request CreateAuthRequestRequestObject

	request.Identifier = identifier

	var body CreateAuthRequestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAuthRequest(ctx, request.(CreateAuthRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAuthRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAuthRequestResponseObject); ok {
		if err := validResponse.VisitCreateAuthRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetClaims operation middleware
func (sh *strictHandler) GetClaims(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, params GetClaimsParams) {
	var request GetClaimsRequestObject

	request.Identifier = identifier
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetClaims(ctx, request.(GetClaimsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClaims")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClaimsResponseObject); ok {
		if err := validResponse.VisitGetClaimsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// CreateClaim operation middleware
func (sh *strictHandler) CreateClaim(w http.ResponseWriter, r *http.Request, identifier PathIdentifier) {
	var request CreateClaimRequestObject

	request.Identifier = identifier

	var body CreateClaimJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateClaim(ctx, request.(CreateClaimRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateClaim")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateClaimResponseObject); ok {
		if err := validResponse.VisitCreateClaimResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetRevocationStatus operation middleware
func (sh *strictHandler) GetRevocationStatus(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, nonce PathNonce) {
	var request GetRevocationStatusRequestObject

	request.Identifier = identifier
	request.Nonce = nonce

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRevocationStatus(ctx, request.(GetRevocationStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRevocationStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRevocationStatusResponseObject); ok {
		if err := validResponse.VisitGetRevocationStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// RevokeClaim operation middleware
func (sh *strictHandler) RevokeClaim(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, nonce PathNonce) {
	var request RevokeClaimRequestObject

	request.Identifier = identifier
	request.Nonce = nonce

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeClaim(ctx, request.(RevokeClaimRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeClaim")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeClaimResponseObject); ok {
		if err := validResponse.VisitRevokeClaimResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetClaim operation middleware
func (sh *strictHandler) GetClaim(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, id PathClaim) {
	var request GetClaimRequestObject

	request.Identifier = identifier
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetClaim(ctx, request.(GetClaimRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClaim")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClaimResponseObject); ok {
		if err := validResponse.VisitGetClaimResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetClaimQrCode operation middleware
func (sh *strictHandler) GetClaimQrCode(w http.ResponseWriter, r *http.Request, identifier PathIdentifier, id PathClaim) {
	var request GetClaimQrCodeRequestObject

	request.Identifier = identifier
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetClaimQrCode(ctx, request.(GetClaimQrCodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClaimQrCode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClaimQrCodeResponseObject); ok {
		if err := validResponse.VisitGetClaimQrCodeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GenerateProof operation middleware
func (sh *strictHandler) GenerateProof(w http.ResponseWriter, r *http.Request, identifier PathIdentifier) {
	var request GenerateProofRequestObject

	request.Identifier = identifier

	var body GenerateProofJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateProof(ctx, request.(GenerateProofRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateProof")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateProofResponseObject); ok {
		if err := validResponse.VisitGenerateProofResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// CreateQueryRequest operation middleware
func (sh *strictHandler) CreateQueryRequest(w http.ResponseWriter, r *http.Request, identifier PathIdentifier) {
	var request CreateQueryRequestRequestObject

	request.Identifier = identifier

	var body CreateQueryRequestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateQueryRequest(ctx, request.(CreateQueryRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateQueryRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateQueryRequestResponseObject); ok {
		if err := validResponse.VisitCreateQueryRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// PublishIdentityState operation middleware
func (sh *strictHandler) PublishIdentityState(w http.ResponseWriter, r *http.Request, identifier PathIdentifier) {
	var request PublishIdentityStateRequestObject

	request.Identifier = identifier

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PublishIdentityState(ctx, request.(PublishIdentityStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PublishIdentityState")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PublishIdentityStateResponseObject); ok {
		if err := validResponse.VisitPublishIdentityStateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// VerifyProof operation middleware
func (sh *strictHandler) VerifyProof(w http.ResponseWriter, r *http.Request, identifier PathIdentifier) {
	var request VerifyProofRequestObject

	request.Identifier = identifier

	var body VerifyProofJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyProof(ctx, request.(VerifyProofRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyProof")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyProofResponseObject); ok {
		if err := validResponse.VisitVerifyProofResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcWXLbOBq+CorTTy7J2uzY1lM7Tpx4upN4S6qStCsFkb8kxCRBA6BstUtnmPd5mmPM",
	"eeYCc4UpLNxBifKWTCcPqVgiln/58G/4qVvHpUFEQwgFd4a3ToQZDkAAM5/E9MDHJJAfPOAuI5EgNHSG",
	"jvoaEQ9CQcYEmNNyiPxeTnFaTogDcIYO8ZyWw+AqJgw8ZyhYDC2Hu1MIsFxSzCM5igtGwomzWLTU9KNs",
	"0cq2R5zHwBrsm3u+7v5vaehCHcehemjdNHlUv9+YsgALSV8onm05rYQAEgqYAHMWkgQGPKIhB6WBrW5X",
	"/ufSUEAo5J84inziYklU5yuXlN3mdviFwdgZOn/rZGrt6Ke88wpCYMR9yRhlb4BzPAG9Y5HP59hDp3AV",
	"AxfOouVsdXtPTcH7EMdiShn5EzxNwtZTk/CWCjSmcaj37/efXgQRo658PvIBHZidFy1n++kBcRQKYCH2",
	"0RmwGTAEcryhpX3AAAvQR1bM1yItYjQCJohGuks9yJ3J9Ei0HL1f9bjqkwZcHL2wH2bzDR19BVeswdki",
	"ObOKsP0JhOLUHMoq3SPqSbYXLWfMaGAlk3jWr8WUAfasxLccQe1fz6O678EuhMwafda0trRVliuZeTlS",
	"DBdq/4uKBFuOVvd+LKbGRCSWYnjrwA0OIl+R4TJQiMD+mVG3MxUi4sNOh+HrzQkR03gUc2AGLJsuDTrS",
	"aA86rjSzbS3/9oy6eNQJMAlT0EocdX77eLA/gYN0l/ZssKkA1spvHWuypZIIE1MPz51hb2/vWXerv9Vy",
	"POrGAYTiXPHY12pyxsT30TURU+QRdfjhJiIMa8D0dnrd7e7u9tZeKpoyJXJKCdgVWZTV1HJu2jQgAoJI",
	"HqEx9jksajgpaqRmZp7mBl6n5QTALn1pbk8pFceUk2Su5cjNUv+YLhzXr8w16UvXtIO3hrcZMF5mTO4/",
	"6Nv8aRH/FVWkB6Aq64borzMLtjNv5ahEIvGW7KxCkJ8n7ueJ+8FOnMH9k561JKTJHbfirh7x3oDAHhaW",
	"aGbkU/fSnWISFs6pE1F/PlGnppHoAxBT6lmXSJz46kVCENeUXRZXCeJghEmzJUpiM0S18kxmu1QlWpqe",
	"l1sT8ddrPZ8mViDOBRawKgJOdjlTg6v4MFGtXi3mS+g9iYHNf8ZEPy30j2mhi/B/OkNdQdEdN1xL4FXq",
	"zHQbkSrJxgKOGaVju2UwKaTjYt8fYffyPfONcRj61MX+lHIx3O12ex05oi2HOBKfOmMfpn9JsrBKs51e",
	"f7C1Le2WSzVbLmFuTMSRPM+ZYvcFDYirlPfm/PhD/114YMy5Ovi9bstpOVfysUrnfZ9eg6drcNwZSlM+",
	"TN1R8tdQu5Zh/+rw6/zg1SHfmr99Gb4/2LoGd+cjPXfpyauD1/ujcPCe7bKtvcMziTVp827EA9vEtu91",
	"LuduYgnbvrfaGN46v/jCGfa7/X6v2+vm6ghVs7ZIs/5Vovj7+eA0/H330/X7nWByAh++Tq6fXb2N5h/P",
	"Pww+7RxMxE0Mzz2+n0j+2c7unsrL1aed8WAX9/YG7e5eb7e9hbd223tj7LYHz7A39ka7o+2tvs7ZVxJy",
	"HL4evNgdxb3Dm3i/vzsZBIJNg1dvb9ztDzP30+Rrv+/OD5/3TIVgWKjhKMm7NAjakY9J2Dbuxcgn0Zwa",
	"1ZbD4tDM3CS0k9T09FK9zW6HZVVGa01ldfGqdK6ey3m1lZiag7+OjZiuM5iuY3ue0E7lyz7qO1MWWl75",
	"qZV3tZKXN2O3TQNdY8wajk8MXcPhqRmUT/hdoHWmVsiMAWYMz6vONMd6SmTGXVO5niQWtyjYsv3NsVMT",
	"Pxgy64KpxOg+evB1d9CWeM6ItpGzphs+S1BRwm/mKh/ehKTOdF0AakxYz3RGcLJ+AwnUxWiRfLwmgXot",
	"9UEZ83j0hZNJiP17g3TRlJHjhOwSN+QLvv9BiciXUWProZfe1/ah8fruA1DJqKAu9e920JSkDKuGotyS",
	"tYAqXR9VFJAz7Fnx4YwGIKYknKApjiKolkOqJYdlBlSo+tAJO6AerLyoqc1Ei1gt1Xry10ZNb3hsRzW/",
	"kI2ZondpObHNh5ZXjpW3yXNiW3r966m6B098NaW+WxWciBU1wl9zzu6eXtOSdS6zB5UstbiGLiypC8QH",
	"L254WEBbkACqB2wtp0U4j3HowgtTUmu4gfLZjTdJHE8OMvf0HJXT92sWPNTWOCzKSVlp2aolmu5lqOR5",
	"WDaMQEt4tpiG14B9MVVxoeepQhL2jwuYNzNGlPqAQ6fiS2sUUSyK2kvbb+NgVNBtrrylBpyTALjAQWQf",
	"o7J3fs4ATikVVhW7qrDk7Yt1IF1fEpbMTqhKWdtkElIGuj9HJh/Uk5PW2ipiMCM05qmQbFVBqrPfpWwy",
	"SsW7sXzMl9ex7U90+8CqcuYS5nligCyH7KausyJ/shIyWsWuK56cnZx080q1HZjjeOQTPi0AsN6kN8DQ",
	"o+ugXkQV5k5BxCws3m68U5EAz5UF15uWicYyL2FdW7ElVdnUTn9v8rWJMRBRlVS4IVyAKcFXzV5IPfiC",
	"45vqxEuYWymaYT9uShEnI5+EE/7AHivjaeWVWuqepHAuWnYwXK66RrWG6hGEnjafd7korI/aPwAj43m5",
	"KF4kaFJTOl83dZb7Teqy37XT3Ir0rWTW7bhSFnXamclBBDwLwpvoIp1uIyCfsjYHseqTAzdm0lRLiZn4",
	"AHPi7sc6NFGSVLTKb4u1Yl0/J+GYVpttX5iLSGVb0JgyJKaAzsAfo9eUC/DQ0Qt07GMhPd8fKoEkQueW",
	"9jFO7pbM6W72NruSHxpBiCPiDJ2B+ko3ACs2OhqBCnBSD4oSdX3yCkSBPKfUs9vXLZpFhnjsusA5wqGH",
	"mDLpXLHkFRglIXp9/uZ3ZPy5knAcBJjN9b7VKUr5xPQxGqe+aDkdaVKJ2/Goyzs4IvLf5hwH/jKuPsrn",
	"D8qMXHENZtBcjSc+LGMr5rVMmJjYzsOD9MyaHSzNpPu+jziwGXGBI8wAsTgMzbkxXbu2hVNKO3JQUUh6",
	"M3cK7qV60pn1OnhieIiotoZFKt7QEfEBqVEIQi+iJJTWqCgn1dPqpA20SR0/JyGZJnXULU9RNpln+Hr9",
	"Z1vQS2v1ZlHugl88okqKDboWzZw/f6HbyBsoQQ66u8ISuQosw4HP5vNFojvTUJK6N4v+XhqVIUHRBATC",
	"vq/OSW5qq3pyj/JP7yXoewUwFclL6ieUerkXCVaJv7e++I0PcoafC97n88XiomxyCoJKtJR2r18ol6Bi",
	"6+Wa0UYPYW0GpXAZ9eUDdV2BZtgnHrqGEScCuPze1XokHDHgNGbqRZGiGpcE+ktP6t0PToOMZFF9JeUh",
	"j26T5MYCqwPsy4gbqWxS/pF0aqUWDxGOzNWR03KmgD1zY7avVNY+0Cpr78sx7XeMTLSh82CMY19m0ht2",
	"s9YUmeUXI9YBqpEAyt+PW419HpI6s0Y4RLm2tSLCSiQ9Dqjs3ZONXELv0Yioh1IyxsjPW9dRPIZVuw92",
	"9FSUU7LFyhl3dJsVbBaqPaPN4IrXxxZ2uMmJKVTtkMt1zKsQO3vH8LNdHNmQTumNQMnt48HW8mLLN0Gu",
	"7RUDW8iZE/1TANi8CLdibL//aC7coFvxnQEqjbZyMLODXJe0GgVfDAQjMAOk56A/wj/ibncA6D///Nd/",
	"//0PtLHBwR9vbKgkaGPD9HRubMj0RQBDLg5RSAUaAYo5eEjQCYgpMJWsVgI4fU9w78PRKnN0qImJgCGN",
	"MCR92iZ6qcN41EaVrjbzbqtuJEhfbtWzz/WtyZI3aFcTMMV8mifA3Rv1BzvdwU5vtDPGu6OBh0d9vD3C",
	"u73Rs93B7lKCXmM+vTtBWmd5YlZ0z73sPf+0M3GDl/S4/1sUzQ6PDz5dzf+cj7bFb3vnz16Bu/36cP/t",
	"SR3N6R3T3Qg2UGSqmuchyhTC2jn6pXnarNndTLPtntZKl25fPhJ0rFKTiNEZ8cDLvZW9WSKpTh7gj+9G",
	"Dgk58UBXELDACSmKsDr+1ccvYwK+t1QDF48Y8FavBG3hrRZv9v7xN45H1s6yUmuWWGb9IwIXawWyepWa",
	"iCJ59h3HEoWX9b5JFFG6Qq4B2o8UOCSwKeOyPlboZFdcpvjYuVU/9LBoXMKRhilbBaUXo5UgoHxl9xDh",
	"QIMZ+t2VRzV7tZeRFlCmbYRPUK+TxiqjDaViXxMfl5AHxWoTp+cgrP2VpRKU3tZ9awj0HxQCl6tN0r7r",
	"QpRaozUsjP6NkFVjtx7Nwmj+7mJhbom3WC8lwYnNrvGRSZTxROjRez1J3LTamz161PTNkZZGWOvDrHPF",
	"kt9ZsaLt1FzmYYSRVBASUyxUKpulsUmAJt3aySk6oDIOp4jLUWPKVFE8UlVZnMXjdnzqlt2/HkpLrcgW",
	"rNLL9SH6vcBOat3VemsCv6QPop2+WbDaQXIIPYSRmoHMAtJB15UZC40a32taYG9Nedq70rqOFnsUloge",
	"PGSu/Mex78//0pmCUYwFfTm8F/Fmx70qN9ypoq5mriip51+4/r7zYNsvI3yTdNj6jroF+id58f9I2bFm",
	"vFpXL2DNDnbVwdmJdP9uM7ybwdndre4CLcPd1hP8MIB/TBPb5BcGkWA45NjVl71SIvon/+SfMriakBnk",
	"bnMXrQfNx5b2WtuaaDJi0dGLtParVwEPGfX9v5UrjRjSC1OUAKzhtanqq5zfObbRbZnu8ugm1x/6vZp6",
	"SzvvE0c2tiba2rgm6Yb9ccOaPPByaM9D7WKhN2CzBGtFUf5OXXVdGGc/V9LpZD9YMuhK1i/StSu/p0t9",
	"H7Q9oeO0cYcjBr6KOAXNdzGYO5ysJ6J1h/XSewmzmkkJ77KU7rPMltKdfouLxf8CAAD//4chvMpSWQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
